name: ll
description: Leafly Lookup.
version: 1.0.0+1
repository: https://github.com/tytydraco/LL
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
